### ISSUE TITLE
Acer A315-51-5647

### ISSUE THREAD

**Issue by ojulianos** [ZeroInfinityXDA/Acer-A315-51-Hackintosh#1]
Hello you have problem with microphone and headphone with this Clover configuration ?

In my case headphone is with noise and microphone too

**Comment by ZeroInfinityXDA** [comment]
Hello there, unfortunately I don't own the laptop anymore. Regarding the headphone jack, it did work for me at one point, but it kernel panicked for me whenever the audio popped (went into idle state). As for the microphone, I didn't test it unfortunately. The issue is most likely related to AppleALC kext, perhaps you can try updating to the latest one here: https://github.com/acidanthera/AppleALC

**Comment by ojulianos** [comment]
Thanks
